#! env zsh

set -e

if [ ! -n "$DOTFILES" ]; then
  DOTFILES=~/.dotfiles
fi
source $DOTFILES/helpers.func.zsh

mkdir -p ~/.claude

install_config $DOTFILES/claude/settings.json ~/.claude/settings.json
install_config $DOTFILES/claude/CLAUDE.md ~/.claude/CLAUDE.md
install_config $DOTFILES/claude/commands ~/.claude/commands

# Sync skills via bin/skills (resolves Skillfile, pins SHAs in Skillfile.lock,
# builds a flat symlink farm at cache/skills/) and point ~/.claude/skills at it.
sync_claude_skills() {
  [ -f "$DOTFILES/claude/Skillfile" ] || return 0
  echo "\033[0;34mSyncing skills...\033[0m"
  "$DOTFILES/claude/bin/skills" install
  install_config "$DOTFILES/claude/cache/skills" "$HOME/.claude/skills"
}

sync_claude_skills

# Generator: emit env exports for the gh-agent machine user. Sourced by zshenv
# inside Claude Code subshells (gated on CLAUDECODE).
claude_bot_env() {
  local gh_dir="$HOME/.config/gh-agent"
  if [ ! -d "$gh_dir" ]; then
    echo "$gh_dir not set up. Run 'GH_CONFIG_DIR=$gh_dir gh auth login' first." >&2
    return 1
  fi

  local info
  if ! info=$(GH_CONFIG_DIR="$gh_dir" gh api user --jq '.login + "|" + (.id|tostring)' 2>&1); then
    echo "gh api user failed: $info" >&2
    return 1
  fi

  local login="${info%|*}"
  local id="${info#*|}"

  cat <<EOF
# Generated by claude/install.sh from \$HOME/.config/gh-agent. Do not edit.
[[ "\$CLAUDECODE" == "1" ]] || return 0

export GH_CONFIG_DIR="\$HOME/.config/gh-agent"
export GIT_SSH_COMMAND="ssh -i \$HOME/.ssh/id_agent -o IdentitiesOnly=yes"
export GIT_AUTHOR_NAME="$login"
export GIT_AUTHOR_EMAIL="$id+$login@users.noreply.github.com"
export GIT_COMMITTER_NAME="$login"
export GIT_COMMITTER_EMAIL="$id+$login@users.noreply.github.com"
EOF
}

generate_config $DOTFILES/zsh/zshenv.d/claude.local.zsh claude_bot_env
