brew "antidote"
brew "fzf"
brew "gh"
brew "git"
brew "golang"
brew "hub"
brew "kubernetes-cli"
brew "kustomize"
brew "libpq"
brew "libpq"
brew "node"
brew "poetry"
brew "pyenv"
brew "rbenv"
brew "tig"

cask "brave-browser"
# cask "google-chrome"
cask "google-cloud-sdk"
cask "iterm2"
cask "karabiner-elements"
cask "little-snitch"
cask "notion"
cask "postico"
cask "postman"
cask "telegram"
cask "time-out"
cask "visual-studio-code"
