WAKATIME_USE_DIRNAME=true

# Set PATH
#
[ -d /usr/local/sbin ] && PATH=/usr/local/sbin:$PATH
[ -d $HOME/.local/bin ] && PATH=$HOME/.local/bin:$PATH
[ -d $HOME/.go ] && export GOPATH=$HOME/.go && PATH=$GOPATH/bin:$PATH

for libpq in /usr/local/Cellar/libpq/*; do
  PATH=$PATH:$libpq/bin
done
export PATH

export ANDROID_HOME=/usr/local/opt/android-sdk
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export PIPENV_VENV_IN_PROJECT=1

[ -f ${HOME}/.dotfiles/zsh/zshalias ] && source ${HOME}/.dotfiles/zsh/zshalias
[ -f ${HOME}/.zshsecrets ] && source ${HOME}/.zshsecrets

